name: math-telegram-bot
platform: python
subdomain: math-bot

build:
  type: pip

run:
  command: python main.py
  web: true

resources:
  memory: 512
  cpu: 1000

env:
  BOT_TOKEN: ${BOT_TOKEN}
  ADMIN_IDS: ${ADMIN_IDS}
